version: '3.1'
services:
  service:
    build:
      context: .
      dockerfile: packages/service/Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm run start:service
